/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PatientCase {
  'sNo' : bigint,
  'sex' : string,
  'birthWeightGrams' : string,
  'screen2Data' : string,
  'babysName' : string,
  'sepsisScreensTable' : string,
  'dateOfBirth' : string,
  'dateOfEnrollment' : string,
  'area' : string,
  'clinicalFeatures' : string,
  'gestationalAgeWeeks' : string,
  'sepsisConfirmed' : string,
  'crNumber' : string,
  'maternalRiskFactors' : string,
  'screen1Data' : string,
  'modeOfDelivery' : string,
  'antibioticsAtScreen' : string,
  'dischargeStatus' : string,
  'indicationCesarean' : string,
  'dateOfDischargeOrDeath' : string,
  'screen3Data' : string,
  'finalDiagnosisAdjudication' : string,
  'finalDiagnosisTreatingTeam' : string,
  'isComplete' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    bigint
  >,
  'deleteCase' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCase' : ActorMethod<[bigint], [] | [PatientCase]>,
  'getCaseCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCases' : ActorMethod<[bigint, bigint], Array<PatientCase>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCases' : ActorMethod<[string], Array<PatientCase>>,
  'updateCase' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];